DATA:
  data_root: data/bdd/bdd100k_dataset_321x185
  train_list: data/bdd/bdd100k_dataset_321x185/train_prefixed.txt
  val_list: data/bdd/bdd100k_dataset_321x185/val_prefixed.txt
  classes: 3

TRAIN:
  train_h: 185
  train_w: 321
  mean_std: 'bdd'
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  ignore_label: 255
  aux_weight: 0.4
  workers: 6  # data loader workers
  batch_size: 16  # batch size for training
  base_lr: 0.001
  epochs: 100
  momentum: 0.9
  output_dir: data/bdd/bdd100k_dataset_321x185/output/predictions/deeplabv3_resnet101_preprocessed
  architecture: deeplab
